### ISSUE TITLE
feature: Add custom scrollbar

### ISSUE THREAD

**Issue by luciano-work** [itsgoingd/clockwork#630]
Hi!
Please, do you can change the default scrollbar?

![MaRhtNuJM6](https://user-images.githubusercontent.com/12519008/229172759-b639782c-7f90-4cfc-964d-ad82af6abde4.png)
Something like this:
```css
::-webkit-scrollbar {
	height: 5px;
	width: 5px;
	background-color: transparent;
}
::-webkit-scrollbar-thumb {
	border-radius: 0.375rem;
	background-color: #e3e3e3;
}
.application.dark ::-webkit-scrollbar {
	height: 5px;
	width: 5px;
	background-color: transparent;
}
.application.dark ::-webkit-scrollbar-thumb {
	border-radius: 0.375rem;
	background-color: #2e2e2d;
}
```
All the best.
